# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [7]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
a = np.random.randint(0, 100, size=(2, 3, 5))
a

array([[[17,  5, 59, 21, 40],
        [ 7, 81, 35, 14, 75],
        [95, 34,  7, 50, 36]],

       [[29, 44, 45, 23, 52],
        [71,  3,  1, 75, 39],
        [56, 89, 96, 30, 72]]])

In [28]:
# Method 2
a = np.ndarray(shape=(2, 3, 5), dtype=int)
a


array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [30]:
# Method 3
a = np.random.rand(2, 3, 5)
a

array([[[0.21887543, 0.7701651 , 0.18654864, 0.14422989, 0.09291855],
        [0.71952096, 0.54049464, 0.44939516, 0.94462967, 0.54160248],
        [0.28426457, 0.70699106, 0.45571484, 0.48959033, 0.8280206 ]],

       [[0.61505613, 0.27982729, 0.57859592, 0.99427555, 0.36197232],
        [0.40383042, 0.96567601, 0.81694262, 0.40655654, 0.99205401],
        [0.83165106, 0.86293924, 0.44711928, 0.57421999, 0.01806137]]])

In [71]:
np.random.random(size=(2, 3, 5))

array([[[0.66442605, 0.9930319 , 0.97128672, 0.22003563, 0.73320576],
        [0.1188299 , 0.43548653, 0.92453736, 0.69477803, 0.01522876],
        [0.70756293, 0.43404884, 0.20871385, 0.15346023, 0.89338863]],

       [[0.36325868, 0.16642481, 0.84336391, 0.04871565, 0.24286182],
        [0.4576731 , 0.88110025, 0.97001187, 0.79113937, 0.48397   ],
        [0.81674879, 0.49966791, 0.88208204, 0.82269474, 0.86277043]]])

#### 4. Print *a*.


In [48]:
# your code here
print(a)

[[[0.21887543 0.7701651  0.18654864 0.14422989 0.09291855]
  [0.71952096 0.54049464 0.44939516 0.94462967 0.54160248]
  [0.28426457 0.70699106 0.45571484 0.48959033 0.8280206 ]]

 [[0.61505613 0.27982729 0.57859592 0.99427555 0.36197232]
  [0.40383042 0.96567601 0.81694262 0.40655654 0.99205401]
  [0.83165106 0.86293924 0.44711928 0.57421999 0.01806137]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [47]:
# your code here
b = np.ones(shape=(5, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [49]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [54]:
# your code here
print(f"Size of a is: {a.size}")
print(f"Size of b is: {b.size}")

Size of a is: 30
Size of b is: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [57]:
# your answer here
c = np.add(a, b)
##can´t add for the arrays have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [59]:
# your code here
c = b.reshape(2, 3, 5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [170]:
# your code/answer here
d = np.add(a, c)
d
## Works for both arrays have the same shape

array([[[1.21887543, 1.7701651 , 1.18654864, 1.14422989, 1.09291855],
        [1.71952096, 1.54049464, 1.44939516, 1.94462967, 1.54160248],
        [1.28426457, 1.70699106, 1.45571484, 1.48959033, 1.8280206 ]],

       [[1.61505613, 1.27982729, 1.57859592, 1.99427555, 1.36197232],
        [1.40383042, 1.96567601, 1.81694262, 1.40655654, 1.99205401],
        [1.83165106, 1.86293924, 1.44711928, 1.57421999, 1.01806137]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [171]:
# your code/answer here
print(a)
print(d)
## Array d is Array a + 1. Since Array b was just ones

[[[0.21887543 0.7701651  0.18654864 0.14422989 0.09291855]
  [0.71952096 0.54049464 0.44939516 0.94462967 0.54160248]
  [0.28426457 0.70699106 0.45571484 0.48959033 0.8280206 ]]

 [[0.61505613 0.27982729 0.57859592 0.99427555 0.36197232]
  [0.40383042 0.96567601 0.81694262 0.40655654 0.99205401]
  [0.83165106 0.86293924 0.44711928 0.57421999 0.01806137]]]
[[[1.21887543 1.7701651  1.18654864 1.14422989 1.09291855]
  [1.71952096 1.54049464 1.44939516 1.94462967 1.54160248]
  [1.28426457 1.70699106 1.45571484 1.48959033 1.8280206 ]]

 [[1.61505613 1.27982729 1.57859592 1.99427555 1.36197232]
  [1.40383042 1.96567601 1.81694262 1.40655654 1.99205401]
  [1.83165106 1.86293924 1.44711928 1.57421999 1.01806137]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [172]:
# your code here
e = np.multiply(a, c)
e

array([[[0.21887543, 0.7701651 , 0.18654864, 0.14422989, 0.09291855],
        [0.71952096, 0.54049464, 0.44939516, 0.94462967, 0.54160248],
        [0.28426457, 0.70699106, 0.45571484, 0.48959033, 0.8280206 ]],

       [[0.61505613, 0.27982729, 0.57859592, 0.99427555, 0.36197232],
        [0.40383042, 0.96567601, 0.81694262, 0.40655654, 0.99205401],
        [0.83165106, 0.86293924, 0.44711928, 0.57421999, 0.01806137]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [173]:
# your code/answer here
## Yes for array c is only ones, so any number multyplied by one, remains the same

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [174]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max is: {d_max}. d_min is: {d_min}. d_mean is: {d_mean}")

d_max is: 1.994275546609464. d_min is: 1.0180613690929796. d_mean is: 1.5507246554872727


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [175]:
# your code here
f = np.empty((2, 3, 5))
f

array([[[0.21887543, 0.7701651 , 0.18654864, 0.14422989, 0.09291855],
        [0.71952096, 0.54049464, 0.44939516, 0.94462967, 0.54160248],
        [0.28426457, 0.70699106, 0.45571484, 0.48959033, 0.8280206 ]],

       [[0.61505613, 0.27982729, 0.57859592, 0.99427555, 0.36197232],
        [0.40383042, 0.96567601, 0.81694262, 0.40655654, 0.99205401],
        [0.83165106, 0.86293924, 0.44711928, 0.57421999, 0.01806137]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [176]:
# your code here
f

array([[[0.21887543, 0.7701651 , 0.18654864, 0.14422989, 0.09291855],
        [0.71952096, 0.54049464, 0.44939516, 0.94462967, 0.54160248],
        [0.28426457, 0.70699106, 0.45571484, 0.48959033, 0.8280206 ]],

       [[0.61505613, 0.27982729, 0.57859592, 0.99427555, 0.36197232],
        [0.40383042, 0.96567601, 0.81694262, 0.40655654, 0.99205401],
        [0.83165106, 0.86293924, 0.44711928, 0.57421999, 0.01806137]]])

In [182]:
print(d)

[[[1.21887543 1.7701651  1.18654864 1.14422989 1.09291855]
  [1.71952096 1.54049464 1.44939516 1.94462967 1.54160248]
  [1.28426457 1.70699106 1.45571484 1.48959033 1.8280206 ]]

 [[1.61505613 1.27982729 1.57859592 1.99427555 1.36197232]
  [1.40383042 1.96567601 1.81694262 1.40655654 1.99205401]
  [1.83165106 1.86293924 1.44711928 1.57421999 1.01806137]]]


In [179]:
v=[]
for x in np.nditer(d):
    if x > d_min and x < d_mean:
        x = 25
    elif x > d_mean and x < d_max:
        x = 75
    elif x == d_mean:
        x = 50
    elif x == d_min:
        x = 0
    elif x == d_max:
        x = 100
    v.append(x)
print(v)


[25, 75, 25, 25, 25, 75, 25, 25, 75, 25, 25, 75, 25, 25, 75, 75, 25, 75, 100, 25, 25, 75, 75, 25, 75, 75, 75, 25, 75, 0]


In [180]:
f = np.array(v).reshape(2, 3, 5)
f

array([[[ 25,  75,  25,  25,  25],
        [ 75,  25,  25,  75,  25],
        [ 25,  75,  25,  25,  75]],

       [[ 75,  25,  75, 100,  25],
        [ 25,  75,  75,  25,  75],
        [ 75,  75,  25,  75,   0]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### Same result without numpy

In [ ]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k]=25
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_max:
                f[i,j,k]=100
print(f)

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [185]:
e = np.empty((2, 3, 5), str)

# your code here
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                e[i, j, k] = "B"
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                e[i,j,k] = "D"
            elif d[i,j,k] == d_mean:
                e[i,j,k] = "C"
            elif d[i,j,k] == d_min:
                e[i,j,k] = "A"
            elif d[i,j,k] == d_max:
                e[i,j,k] = "E"
print(e)

[[['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'B']
  ['B' 'D' 'B' 'B' 'D']]

 [['D' 'B' 'D' 'E' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'A']]]
